import os
from dotenv import load_dotenv

load_dotenv()

MODEL_SERVER_URL = os.getenv("MODEL_SERVER_URL")

NAVER_TTS_CLIENT_ID = os.getenv("NAVER_TTS_CLIENT_ID")
NAVER_TTS_CLIENT_SECRET = os.getenv("NAVER_TTS_CLIENT_SECRET")

NAVER_STT_CLIENT_ID = os.getenv("NAVER_STT_CLIENT_ID")
NAVER_STT_CLIENT_SECRET = os.getenv("NAVER_STT_CLIENT_SECRET")